### ISSUE TITLE
Plugin crash when 'Enable Network Access' enabled in the Utility

### ISSUE THREAD

**Issue by FrostyCoolSlug** [parzival-space/obs-goxlr-fader-sync-plugin#3]
This one's on me, because it's not documented..

When 'Enable Network Access' is enabled in the Utility's Settings, the reported bind_address will be `0.0.0.0` (indicating it's binding to all IPs). In this scenario, you need to tweak the host to be `localhost` instead to connect. 

Currently having this setting enabled will crash OBS when it tries to load the plugin.

**Comment by parzival-space** [comment]
Alright, I will fix that once I am home. 👍

**Comment by parzival-space** [comment]
Should be fixed now. But if you want to verify this, you can download the current build artifacts here:
[https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/actions/runs/8941910744](https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/actions/runs/8941910744)
