### ISSUE TITLE
Muting Channel in GoXLR does not Mute Channel in OBS 

### ISSUE THREAD

**Issue by ridaztor** [parzival-space/obs-goxlr-fader-sync-plugin#7]
I just Tried out this plugin and it is amazing. Thank you very much. I just relized, when i Mute the Music channel on my GoXLR, the Channel isnt Muted on stream. 

Is this not supported or is there somthing i have to do in order for this to work?

Thanks

**Comment by parzival-space** [comment]
No you are absolutely right. I just tested it and can reproduce the problem.
This is definitely a bug.

Could you please test what happens when you hold the mute button for a few seconds?
The GoXLR should then use the MuteToAll behavior.

**Comment by ridaztor** [comment]
I will check as soon as i can, thanks for your quick reply

**Comment by parzival-space** [comment]
I did some tests and I think I was able to fix the bug.

You can download the test build from this link. Just scroll to the bottom of the page and download the Windows/Linux-artifact. 
https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/actions/runs/9356581253

Please also let me know if this actually fixed your problem :)

**Comment by ridaztor** [comment]
Just tested the Test Build, it works like a charm. Thanks very much

**Comment by parzival-space** [comment]
Perfect, I will merge this into development then.
Thank you for reporting this issue.
